#!/usr/bin/with-contenv sh
LOCKFILE="/var/lock/`basename $0`"

if [ "$SKIP_BACKUP" = "true" ]; then
 echo "Skipping backup"
 exit 0
fi

(
  # Wait for lock for 5 seconds
  flock -x -n 200 || exit 1

# Sync drive-media


/scripts/backup.sh


echo "Syncying drive-media: $command"

exec $command



) 200> ${LOCKFILE}
