#!/usr/bin/with-contenv sh
LOCKFILE="/var/lock/`basename $0`"

if [ $SKIP_UPLOAD = "true" ]; then
 echo "Skipping upload"
 exit 0
fi

(
  # Wait for lock for 5 seconds
  flock -x -n 200 || exit 1

# Move older local files to the cloud


command="/usr/sbin/rclone --config /config/rclone.conf move /local-media $REMOTE_PATH $UPLOAD_ARGS"


echo "Uploading local: $command"

exec $command



) 200> ${LOCKFILE}
