#!/usr/bin/with-contenv sh
LOCKFILE="/var/lock/`basename $0`"

START_TIME=$SECONDS

echo "Waiting for warming up cache" | tee "/logs/warm-cache.log"

sleep 60

/scripts/warm-mount-cache.sh

echo "Cache warmed up | tee -a "/logs/warm-cache.log"
ELAPSED_TIME=$((${SECONDS} - ${START_TIME}))
echo "Cache warmed up in ${ELAPSED_TIME}s" | tee -a "/logs/warm-cache.log"
