#!/usr/bin/with-contenv sh

#rclone_command="/usr/sbin/rclone --config /config/rclone.config mount $RemotePath /mnt/drive $MountCommands"
#
#echo "Mounting rclone folder: $rclone_command"
#
#exec $rclone_command
#
#exit 0
#